### PR TITLE
Providing an alternative solution for the DF.13 and DF.14 latch-up ru…

### LINKED ISSUE #103: Is this fork active?
If it is, I have some feedback.

Thanks,

Matthias

### PR DESCRIPTION
**Pull request by klayoutmatthias**
Fixes #103

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

Please see ticket for details.
As a side effect, the modified solution - although more complex because of the incremental size loop - reduces the "comp" section run times from 1300s to 280s in one test case of mine.

### CODE REVIEW

**Comment by proppy** [comment]
@atorkmabrains this was mention in the FSiC talk today: https://wiki.f-si.org/index.php?title=Learning_from_GF180_PDK:_Best_practices_for_implementing_and_optimizing_KLayout_DRC_and_LVS_decks

**Comment by proppy** [comment]
@atorkmabrains it's happening right now!

**Comment by klayoutmatthias** [comment]
Slides are available (https://wiki.f-si.org/images/1/19/FSiC2023_KLayout_DRCLVS_best_practices.pdf) :)

**Comment by atorkmabrains** [comment]
Thanks @klayoutmatthias Looking forward to the video as well.

**Review by FaragElsayed2 — APPROVED** [review]

**Comment by FaragElsayed2** [comment]
Reviewed and tested. 

Thanks for your support @klayoutmatthias 

Cc @atorkmabrains

**Pull request merged**
