### PR TITLE
Fixing some rules in NP/PP table for GF180MCU DRC

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Fixing some rules in NP/PP table for GF180MCU DRC

- Fixing https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv/issues/45 issue
- Fixing #80 
- Fixing #77

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Could you please add screenshots of the changed test structures?

**Comment by FaragElsayed2** [comment]
@atorkmabrains 

- For NP.11

Old pass
image

New pass
image

Old Fail
image

New Fail
image

- For PP.11

Old pass
image

New pass
image

Old Fail
image

New Fail
image

- For NP.5b [Similar to PP.5b]

Adding some pass patterns for butting N/P to test this case

image

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Pull request merged**
