### PR TITLE
Fixing MDN.17 rule and testcase for GF180MCU DRC

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Fixing MDN.17 rule and testcase for GF180MCU DRC

- Fixing #79

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Could you please add a screenshot here for the update in the test structure that you have added?

**Comment by FaragElsayed2** [comment]
Adding new fail pattern to cover broken Psub ring

image

image

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Pull request merged**
