### PR TITLE
fixing MT30.8 rule issue and adding testcase

### PR DESCRIPTION
**Pull request by RehabSayed-G**
Fixes #<issue_number_goes_here>

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by FaragElsayed2 — APPROVED** [review]

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , ready for review

**Review by FaragElsayed2 — CHANGES_REQUESTED** [review]
@RehabSayed-G 

- It fails in CI [Linting issues]
- You need to add this switch to run script to be able to use it

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , ready for review

**Review by FaragElsayed2 — CHANGES_REQUESTED** [review]
@RehabSayed-G Please update README file in drc dir to reflect new added switch [Update usage section for options --> Variants also need to be updated]

**Comment by RehabSayed-G** [comment]
@FaragElsayed2 , ready for review

**Review by FaragElsayed2 — APPROVED** [review]

**Pull request merged**
