### PR TITLE
Adding density rules for GF180MCU DRC

### PR DESCRIPTION
**Pull request by FaragElsayed2**
## Adding density rules for GF180MCU DRC

### CODE REVIEW

**Comment by FaragElsayed2** [comment]
@atorkmabrains Ready to review

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Could you please resolve the conflict for this PR?

**Comment by FaragElsayed2** [comment]
@atorkmabrains Done

**Review by atorkmabrains — APPROVED** [review]
Thanks @FaragElsayed2

**Pull request merged**
